### PR TITLE
Fix issue where, in some situations, the immediate-invoker helper manager (used when you use `resourceFactory`) was not correctly destroying the previous instance of a resource (such as when args change))

### LINKED ISSUE #1134: Potential issue with non-block updates deferring cleanup to their parent context
See [Demo](https://limber.glimdown.com/edit?c=JYWwDg9gTgLgBAYQuCA7Apq%2BAzKy4DkAAgOYA2oI6UA9AMbKQZYEDcAUKJLHAN5wwoAQzoBrdABM4AXzi58xcpWo1BI0cFQk2nFD35oZcvCEJF0IAEYqQECcGzBqOrtHgAJdGTDVjC81YqDCjMMDQAFl4%2BUC568PxQ6CTAAM4w1AAi6GlQAK50MNBG8qbEFta0EtmCEACeQpZk6LHc8XCJKRC5UHToADRwvWRkAx1dPegAYiKFULXFJoTl1AC0Y929KTrsDKhpcAAyAPIIAIIHAKIAynAAvHAA2uxwS6grAKpXBH3PrysA4gAhb6-AiiCArADSRxBLwIACshCsAFIABRWuRWdCRiLAQgwKWaPwAuhwdmQhCkUocINimqjgGJfOgAB7pVASalIEKYeK-IhqJlSMi0oRNO5-T46F4C4RCuDhYBVCXYMWEskvXJgCRCdISgAU6AAlHcAHwCRUpAB0Irp6Al6CtMCEUBI6BgVoAbmLcugOC9CiRyPb7vqTbdzTBLVbFcr7gBCKOpGNKv3sX5u%2BCpK7hCAAd00JDDfF%2BL0SMG6qDgiejsbTL2kv1%2BAB50uAKelTaW4M37J7BhSqbcAEQU2pdGDDrsvGc9xxeTnu03Nppujmmq7umCFlLNmirzASaezmcrhpeU0HUVNbsnnuEpoFPi8QwEOjhfFuggW5NanXpaRpGPO9Z14XgAGJ0BEcJDhOc5rjgSk4AAH1tMV0GQwDbxAl5mwgMBt0Mb0yF9W4wLQppANNcjr3QQC93wwjUGAnDnxoKD3yw1iexoB90AKFjZz3ClrDIQTTxEi9sNndxU0GNB2RgAB%2BaTT00MBcngGBah8Ed3340RLAgFlh2fV930-Zof2tQNgyo1ThPPMTsL3ecyEXGBj1UlyUjxZjVLA8CHGsq1s1zAstC41iwNqJx3JCii6MbHCwJoBwoqE3i-JYvc%2B2PPc2zADt0C7Rt2GwXJUAKYBDAAFVAdB9RAFITV4X5y0rdpsnGXp9X1Awq2kcNzTa2cmi0hqJSGMh9QyXVHVQfMwyNf0Z3GuBNHSKBiIlQkYAASSwahiL64aBAaq06G6RIsAlOb0itRa8zDAZmpW9NZzQS6mnxLVTrNAcoKgQ6tpOzbjrFI13u7DqoCrbcqFWoaOEbdYJmmApoFqfV6qoaHdn2BBbVECU0d6-q4FyQkZDO0auorOHKcJHGGv1ABGAB9AAGHmoZR6GaBoPxTCEOAwEST0aqpuBWSEdt0HKyrqsMSZoBAXV0gkInaVEfVEolAhMA%2BL4TRLF51uwNWNd8e4MDzOAQbIK17vQXGpitmA9dogY6ZeWwsHCAAuQgRS0WEZx1Wpg4IVBcioKBGXDl5c26aPY-jxOflnEBNE09A07j6hM%2B7QldgkAuM7oJOFXGNmACZg8EX0s5p1aCYgJobQgIsAAMEESXVC0QuA7eDgASXhEukHujQ%2B%2BnOrJxqKap-o4EMIaAd9uB1oRkMmca7WxHe2d287kVe72rVx8n2jp9n7svroH7Y7Af6IzNk9T8dc-9R7p%2BoJftfKeM9VoNnvrOWGVZizv0tlAdWMAtpWlgfA-Uu9LrXV5MfVu7BUbdQ2FMGYWN9SqzgdbLWxNobkkpNSC4LIn5CFADLNkh5qSeG8L4OmBMm6YygPqK0-CXQkBah-F4KQtTUD4QI10LVuxfy7kWAgtD6GgGDodYA24xTyT2NwpiBAsFliSKkLaWQcj5FmKgy0AxoHmjkT-RRdCKQqLgJMTQmiqimOVqgPRWDkrb0pDANujA876geIlYkrVuzBQscmQcMAIl3lsd3fU9jlEgGDlcUAuRiqA1%2BmAPRoCZDdiTNaWJEpEoFNkWgToZ8kn2McWkxAQT0j5Jhu6TqPcJ5T3jD3JGOD0ytgsEVea%2BUrx2gZEyKAiFqSoVoshFi%2B0swpGDq2Bq1FeAkPgZrQ%2BJMp7SAKqs5slhJk0BykcliVMh5RntM2BgVQ1lKPqdvW%2Bez6B2BKk8u0q09yjPQuM8QUBzRz2bGkWoTQWJuQ8gMPiT4t4vCMlAKoUBg5szACyOA1SlQFJeHiCQ9gtDBy5laAArIkEABTfEvAhXtEREdUhDKjnIJoLIsVwBIEIMABLiWkpZdgJlKx7CJE8cHBgJEQCoHJd2G0QhxyaRpS8ewvkxzB15ayFlbKOVwDrty7CYpgAkDeOoiwSzBi8moBK3CvFtJgvYAVQZxUuxAA&format=gjs)

Needs further investigation in a test environment

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Fix #1134

The issue seems specific to vanilla rendering, where your resource isn't surrounded with an if block.

### CODE REVIEW

File: ember-resources/src/function-based/immediate-invocation.ts [hunk 1]
```diff
@@ -14,9 +14,6 @@ type ResourceFactory<Value = any, Args = any> = (...args: SpreadFor<Args>) => Va
 
 interface State {
   cache: ReturnType<typeof invokeHelper>;
-  fn: any;
```
Comment (NullVoxPopuli) [inline ember-resources/src/function-based/immediate-invocation.ts:17]: These were all unused

File: ember-resources/src/function-based/immediate-invocation.ts [hunk 2]
```diff
@@ -51,12 +49,20 @@ class ResourceInvokerManager {
 
       setOwner(resource, this.owner);
 
-      return invokeHelper(cache, resource);
+      let result = invokeHelper(cache, resource);
+
+      if (previous) {
+        destroy(previous);
```
Comment (NullVoxPopuli) [inline ember-resources/src/function-based/immediate-invocation.ts:55]: the fix

File: ember-resources/src/function-based/immediate-invocation.ts [hunk 3]
```diff
@@ -72,6 +78,9 @@ class ResourceInvokerManager {
   }
 
   getDestroyable({ cache }: State) {
+    /**
+     * This is the parent cache, from `createHelper`
```
Comment (NullVoxPopuli) [inline ember-resources/src/function-based/immediate-invocation.ts:82]: with nested caches, I had a hard time knowing which thing I was dealing with when, so I added some context

File: ember-resources/src/function-based/resource.ts [hunk 4]
```diff
@@ -186,6 +186,7 @@ export function resource<Value>(
     let internalConfig: InternalFunctionResourceConfig<Value> = {
       definition: context as ResourceFunction<Value>,
       type: 'function-based',
+      name: 'Resource',
```
Comment (NullVoxPopuli) [inline ember-resources/src/function-based/resource.ts:189]: Helps with debug output when errors from Glimmer print to the console

File: ember-resources/src/function-based/resource.ts [hunk 5]
```diff
@@ -222,10 +223,19 @@ export function resource<Value>(
...
   };
 
   setHelperManager(ResourceManagerFactory, internalConfig);
 
   return wrapForPlainUsage(context, internalConfig);
 }
+
+function getDebugName(obj: object) {
+  if ('name' in obj) {
+    return `Resource Function: ${obj.name}`;
```
Comment (NullVoxPopuli) [inline ember-resources/src/function-based/resource.ts:237]: Helps with debug output when errors from Glimmer print to the console

File: ember-resources/tsconfig.json [hunk 6]
```diff
@@ -42,15 +42,21 @@
     "allowImportingTsExtensions": true,
 
     // require extensions
-    "module": "Node16",
-    "moduleResolution": "Node16",
+    // "module": "Node16",
```
Comment (NullVoxPopuli) [inline ember-resources/tsconfig.json:45]: fixes local dev experience

File: test-app/ember-cli-build.js [hunk 7]
```diff
@@ -1,11 +1,16 @@
...
+const path = require('path');
 const EmberApp = require('ember-cli/lib/broccoli/ember-app');
 
 const packageJson = require('./package');
 
 module.exports = function (defaults) {
+  const sideWatch = require('@embroider/broccoli-side-watch');
   let app = new EmberApp(defaults, {
+    trees: {
+      app: sideWatch('app', { watching: [path.join(__dirname, '../ember-resources')] }),
```
Comment (NullVoxPopuli) [inline test-app/ember-cli-build.js:12]: allows me to not have to restart the app when I re-compile the addon (which is an injected dependency)
