### PR TITLE
Fix use types

### LINKED ISSUE #1128: Incompatible types on yielded block
Assuming following code:

```gts
import Component from '@glimmer/component';
import { service } from '@ember/service';
import type SettingsService from 'the-mountains-are-calling/services/settings';
import { firebaseQuery } from 'the-mountains-are-calling/builders/firebase';
import { use, cell, resource, type Reactive } from 'ember-resources';
import { Cell } from '@starbeam/universal';

export type ClockNakedSignature = {
  percentage: Cell<number>;
  counter: Cell<number>;
};

export type ClockSignature = Reactive<ClockNakedSignature>;

interface Signature {
  Args: {};
  Blocks: {
    default: [ClockNakedSignature];
  };
  Element: HTMLDivElement;
}

const Clock = resource(({ on }) => {
  const counter = cell(0);
  const percentage = cell(0);

  return { percentage, counter };
});

export default class Refresher extends Component<Signature> {
  clock = use(this, Clock);

  <template>{{yield this.clock}}</template>
}
```

The line `clock = use(this, Clock);` reports following error:

```
Public property 'clock' of exported class has or is using name 'CURRENT' from external module "/Users/michal/pudr.com/the-mountains-are-calling/node_modules/.pnpm/ember-resources@7.0.0_@glimmer+component@1.1.2_@glimmer+tracking@1.1.2_@glint+template@1.4.0_ember-source@5.6.0/node_modules/ember-resources/declarations/index" but cannot be named.glint(4029)
```

And line `<template>{{yield this.clock}}</template>` reports following error:

```
Argument of type 'Reactive<{ percentage: Cell<number>; counter: Cell<number>; }>' is not assignable to parameter of type 'ClockNakedSignature'.
  Type 'Reactive<{ percentage: Cell<number>; counter: Cell<number>; }>' is missing the following properties from type 'ClockNakedSignature': percentage, counterglint(2345)
```

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Fix #1128 

Issues:
- `CURRENT` symbol was exposed, and caused interface matching to fail -- it has been cast to a non-symbol via the same lies @runspired is using in ember-data :sweat_smile: 

Unresolved:
- need to better declare the differences in the `use` apis

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
@MichalBryxi, would you like to review?

File: ember-resources/src/function-based/types.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@ export interface InternalFunctionResourceConfig<Value = unknown> {
   [INTERNAL]: true;
 }
 
-export const CURRENT = Symbol('ember-resources::CURRENT');
+export const CURRENT = Symbol('ember-resources::CURRENT') as unknown as 'CURRENT';
```
Comment (NullVoxPopuli) [inline ember-resources/src/function-based/types.ts:13]: this is the fix: typescript has been annoying with symbols and inferred types lately. :(

**Comment by MichalBryxi** [comment]
Question: The test checks that Ember code works. But does that also prove that TS won't report problems? My example code compiled just fine. I was only getting squiggly line under respective TS code.

Is that guaranteed because the TS checks on the testing source code would fail?

**Comment by NullVoxPopuli** [comment]
> Is that guaranteed because the TS checks on the testing source code would fail?

yeah, from all of
image

image

image
